### PR TITLE
5 django basic start project

### PR DESCRIPTION
**Pull request by KristofferKarlAxelEkstrand**

### CODE REVIEW

**Review by Noragiri — APPROVED** [review]

**Review by Noragiri — APPROVED** [review]

**Review by VMJ82 — APPROVED** [review]

**Review by arslanakram123 — COMMENTED** [review]
looks good :D

**Review by arslanakram123 — COMMENTED** [review]
looks good :D

**Comment by malahat14** [comment]
looks nice

**Review by arslanakram123 — APPROVED** [review]

**Review by malahat14 — APPROVED** [review]
approve

**Comment by KristofferKarlAxelEkstrand** [comment]
[create basic app](https://trello.com/c/xxRZkLC9/23-create-basic-app)

**Pull request merged**
